//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
var timeInterval; $(document).ready(function() {paintOk();randomSort();timeInterval=setInterval("paintTab()",1000);
var canWidth=$("#ardoraAct").css("width").replace("px","");var canHeight=$("#ardoraAct").css("height").replace("px","");$("#ardoraActCanvas").attr({"width": canWidth,"height": canHeight})
$("#ardoraActCanvasAnim").attr({"width": canWidth,"height": canHeight});
$("#buttonOk").mouseenter(function(){$(this).css("-webkit-box-shadow"," 0px 0px 0px rgba(50, 50, 50, 0.5)");
$(this).css("box-shadow" , "0px 0px 0px rgba(50, 50, 50, 0.75)");removeOk();
}).mouseleave(function() { $(this).css("-webkit-box-shadow"," 4px 4px 4px rgba(50, 50, 50, 0.5)"); $(this).css("-moz-box-shadow", "4px 4px 4px rgba(50, 50, 50, 0.5)");$(this).css("box-shadow" , "4px 4px 4px rgba(50,50,50,0.5)"); paintOk();}).mousedown(function(){if (typeGame!=99){isCorrect();}})
$("#ardoraEnu").click(function(){if (!isPlayEnu){ document.getElementById("audioEnu").play();isPlayEnu=true;}
else{document.getElementById("audioEnu").pause(); isPlayEnu=false;}});
initAct();})
function paintOk() {document.getElementById("outerRect").setAttribute("fill", colorButton);document.getElementById("stop1").setAttribute("stop-color", colorBack);document.getElementById("stop2").setAttribute("stop-color", colorSele);document.getElementById("innerRect").setAttribute("stroke", colorText);document.getElementById("buttonText").setAttribute("fill", colorText);}
function removeOk() {document.getElementById("outerRect").setAttribute("fill", colorSele);document.getElementById("stop1").setAttribute("stop-color", colorBack);document.getElementById("stop2").setAttribute("stop-color", colorButton);document.getElementById("innerRect").setAttribute("stroke", colorText);document.getElementById("buttonText").setAttribute("fill", colorText);}
function paintTab() {var svgNS = "http://www.w3.org/2000/svg";var container = document.getElementById("ardoraTab");var oldSVG = document.getElementById("ardoraTabSVG");if (oldSVG) {container.removeChild(oldSVG);};var totalHeight = 1;if (tiTime) {totalHeight += 85 + 3;};if (tiSuccesses) {totalHeight += 45 + 3;};if (tiAttempts) {totalHeight += 45 + 3;};if (tiScore) {totalHeight += 45;};totalHeight=totalHeight+3;var svg = document.createElementNS(svgNS, "svg");svg.setAttribute("id", "ardoraTabSVG");svg.setAttribute("width", "70");svg.setAttribute("height", totalHeight.toString());
var defs = document.createElementNS(svgNS, "defs");if (tiTime) {if (!isShowMessage) {timeAct -= 1;};if (timeAct == 0) {goTime();};var gradTimer = document.createElementNS(svgNS, "radialGradient");gradTimer.setAttribute("id", "gradTimer");gradTimer.setAttribute("cx", "35");gradTimer.setAttribute("cy", "54");gradTimer.setAttribute("r", "25");gradTimer.setAttribute("fx", "35");gradTimer.setAttribute("fy", "54");
var stop1 = document.createElementNS(svgNS, "stop");stop1.setAttribute("offset", "0%");stop1.setAttribute("stop-color", colorBack);gradTimer.appendChild(stop1);var stop2 = document.createElementNS(svgNS, "stop");stop2.setAttribute("offset", "100%");stop2.setAttribute("stop-color", colorButton);gradTimer.appendChild(stop2);defs.appendChild(gradTimer);};svg.appendChild(defs);
var profundidade = 1;if (tiTime) {var timerGroup = document.createElementNS(svgNS, "g");var rectFondo = document.createElementNS(svgNS, "rect");rectFondo.setAttribute("x", "1");rectFondo.setAttribute("y", "1");rectFondo.setAttribute("width", "68");rectFondo.setAttribute("height", "85");rectFondo.setAttribute("fill", colorButton);timerGroup.appendChild(rectFondo);var rectSup = document.createElementNS(svgNS, "rect");rectSup.setAttribute("x", "3");rectSup.setAttribute("y", "3");rectSup.setAttribute("width", "64");rectSup.setAttribute("height", "18");rectSup.setAttribute("fill", colorBack);rectSup.setAttribute("stroke", colorBack);rectSup.setAttribute("stroke-width", "1");timerGroup.appendChild(rectSup);
var textoTempo = document.createElementNS(svgNS, "text");textoTempo.setAttribute("x", "8");textoTempo.setAttribute("y", "15");textoTempo.setAttribute("fill", colorText);textoTempo.setAttribute("font-family", "Verdana");textoTempo.setAttribute("font-size", "8px");textoTempo.textContent = "TIEMPO:";timerGroup.appendChild(textoTempo);
var circulo = document.createElementNS(svgNS, "circle");circulo.setAttribute("cx", "35");circulo.setAttribute("cy", "54");circulo.setAttribute("r", "25");circulo.setAttribute("fill", "url(#gradTimer)");timerGroup.appendChild(circulo);var strokeColor = (timeAct > timeIni / 4) ? colorSele : "red";var circuloBorde = document.createElementNS(svgNS, "circle");circuloBorde.setAttribute("cx", "35");circuloBorde.setAttribute("cy", "54");circuloBorde.setAttribute("r", "25");circuloBorde.setAttribute("fill", "none");circuloBorde.setAttribute("stroke", strokeColor);circuloBorde.setAttribute("stroke-width", "5");timerGroup.appendChild(circuloBorde);
if(timeAct <= timeIni) {var fraction = timeAct / timeIni;var arcAngle = fraction * 2 * Math.PI;var startAngle = 1.5 * Math.PI;var endAngle = startAngle + arcAngle;function polarToCartesian(cx, cy, r, angle) {return { x: cx + r * Math.cos(angle), y: cy + r * Math.sin(angle) };};var start = polarToCartesian(35, 54, 25, startAngle);var end = polarToCartesian(35, 54, 25, endAngle);var largeArcFlag = (arcAngle > Math.PI) ? "1" : "0";var d = "M " + start.x + " " + start.y + " A 25 25 0 " + largeArcFlag + " 1 " + end.x + " " + end.y;var pathArc = document.createElementNS(svgNS, "path");pathArc.setAttribute("d", d);var arcStroke = (timeAct > timeIni / 4) ? colorButton : colorSele;pathArc.setAttribute("fill", "none");pathArc.setAttribute("stroke", arcStroke);pathArc.setAttribute("stroke-width", "2");timerGroup.appendChild(pathArc);}
var textoTimeAct = document.createElementNS(svgNS, "text");textoTimeAct.setAttribute("x", "35");textoTimeAct.setAttribute("y", "58");textoTimeAct.setAttribute("fill", colorText);textoTimeAct.setAttribute("font-family", "Verdana");textoTimeAct.setAttribute("font-size", "10px");textoTimeAct.setAttribute("text-anchor", "middle");textoTimeAct.textContent = timeAct;timerGroup.appendChild(textoTimeAct);svg.appendChild(timerGroup);profundidade = 1 + 85 + 3;}
if (tiSuccesses) {var successesGroup = document.createElementNS(svgNS, "g");var rectFondo = document.createElementNS(svgNS, "rect");rectFondo.setAttribute("x", "1");rectFondo.setAttribute("y", profundidade.toString());rectFondo.setAttribute("width", "68");rectFondo.setAttribute("height", "45");rectFondo.setAttribute("fill", colorButton);successesGroup.appendChild(rectFondo);var rectInterno = document.createElementNS(svgNS, "rect");rectInterno.setAttribute("x", "3");rectInterno.setAttribute("y", (profundidade + 2).toString());rectInterno.setAttribute("width", "64");rectInterno.setAttribute("height", "18");rectInterno.setAttribute("fill", colorBack);rectInterno.setAttribute("stroke", colorSele);rectInterno.setAttribute("stroke-width", "1");successesGroup.appendChild(rectInterno);
var textoAcertos = document.createElementNS(svgNS, "text");textoAcertos.setAttribute("x", "8");textoAcertos.setAttribute("y", (profundidade + 14).toString());textoAcertos.setAttribute("fill", colorText);textoAcertos.setAttribute("font-family", "Verdana");textoAcertos.setAttribute("font-size", "8px");textoAcertos.textContent = "ACIERTOS:";successesGroup.appendChild(textoAcertos);
var textoValores = document.createElementNS(svgNS, "text");textoValores.setAttribute("x", "35");textoValores.setAttribute("y", (profundidade + 40).toString());textoValores.setAttribute("fill", colorBack);textoValores.setAttribute("font-family", "Verdana");textoValores.setAttribute("font-size", "14px");textoValores.setAttribute("font-weight", "bold");textoValores.setAttribute("text-anchor", "middle");textoValores.textContent = successes + "/" + successesMax;successesGroup.appendChild(textoValores);svg.appendChild(successesGroup);profundidade += 45 + 3;}
if (tiAttempts) {var attemptsGroup = document.createElementNS(svgNS, "g");var rectFondo = document.createElementNS(svgNS, "rect");rectFondo.setAttribute("x", "1");rectFondo.setAttribute("y", profundidade.toString());rectFondo.setAttribute("width", "68");rectFondo.setAttribute("height", "45");rectFondo.setAttribute("fill", colorButton);attemptsGroup.appendChild(rectFondo);var rectInterno = document.createElementNS(svgNS, "rect");rectInterno.setAttribute("x", "3");rectInterno.setAttribute("y", (profundidade + 2).toString());rectInterno.setAttribute("width", "64");rectInterno.setAttribute("height", "18");rectInterno.setAttribute("fill", colorBack);rectInterno.setAttribute("stroke", colorSele);rectInterno.setAttribute("stroke-width", "1");attemptsGroup.appendChild(rectInterno);
var textoIntentos = document.createElementNS(svgNS, "text");textoIntentos.setAttribute("x", "8");textoIntentos.setAttribute("y", (profundidade + 14).toString());textoIntentos.setAttribute("fill", colorText);textoIntentos.setAttribute("font-family", "Verdana");textoIntentos.setAttribute("font-size", "8px");textoIntentos.textContent = "INTENTOS:";attemptsGroup.appendChild(textoIntentos);
var textoAttempts = document.createElementNS(svgNS, "text");textoAttempts.setAttribute("x", "35");textoAttempts.setAttribute("y", (profundidade + 40).toString());var fillAtt = ((attemptsMax - attempts) > 1) ? colorBack : "red";textoAttempts.setAttribute("fill", fillAtt);textoAttempts.setAttribute("font-family", "Verdana");textoAttempts.setAttribute("font-size", "14px");textoAttempts.setAttribute("font-weight", "bold");textoAttempts.setAttribute("text-anchor", "middle");textoAttempts.textContent = attempts + "/" + attemptsMax;attemptsGroup.appendChild(textoAttempts);svg.appendChild(attemptsGroup);profundidade += 45 + 3;}
if (tiScore) {var scoreGroup = document.createElementNS(svgNS, "g");var rectFondo = document.createElementNS(svgNS, "rect");rectFondo.setAttribute("x", "1");rectFondo.setAttribute("y", profundidade.toString());rectFondo.setAttribute("width", "68");rectFondo.setAttribute("height", "45");rectFondo.setAttribute("fill", colorButton);scoreGroup.appendChild(rectFondo);var rectInterno = document.createElementNS(svgNS, "rect");rectInterno.setAttribute("x", "3");rectInterno.setAttribute("y", (profundidade + 2).toString());rectInterno.setAttribute("width", "64");rectInterno.setAttribute("height", "18");rectInterno.setAttribute("fill", colorBack);rectInterno.setAttribute("stroke", colorSele);rectInterno.setAttribute("stroke-width", "1");scoreGroup.appendChild(rectInterno);
var textoPuntos = document.createElementNS(svgNS, "text");textoPuntos.setAttribute("x", "8");textoPuntos.setAttribute("y", (profundidade + 14).toString());textoPuntos.setAttribute("fill", colorText);textoPuntos.setAttribute("font-family", "Verdana");textoPuntos.setAttribute("font-size", "8px");textoPuntos.textContent = "PUNTOS:";scoreGroup.appendChild(textoPuntos);
var textoScore = document.createElementNS(svgNS, "text");textoScore.setAttribute("x", "35");textoScore.setAttribute("y", (profundidade + 40).toString());textoScore.setAttribute("fill", colorBack);textoScore.setAttribute("font-family", "Verdana");textoScore.setAttribute("font-size", "14px");textoScore.setAttribute("font-weight", "bold");textoScore.setAttribute("text-anchor", "middle");textoScore.textContent = score + "/" + scoreMax;scoreGroup.appendChild(textoScore);svg.appendChild(scoreGroup);};if (tiTime || tiSuccesses || tiAttempts || tiScore){container.appendChild(svg);}}
 function printJustify(context, text, x, y, lineHeight, fitWidth) { fitWidth = fitWidth || 0; lineHeight = lineHeight || 20; var outLines=[]; var currentLine = 0;
var lines = text.split(/\r\n|\r|\n/); for (var line = 0; line < lines.length; line++) { if (fitWidth <= 0) { context.fillText(lines[line], x, y + (lineHeight * currentLine));
} else { var words = lines[line].split(" "); var idx = 1; while (words.length > 0 && idx <= words.length) { var str = words.slice(0, idx).join(" ");
var w = context.measureText(str).width; if (w > fitWidth) { if (idx == 1) { idx = 2;} outLines.push(words.slice(0, idx - 1).join(" "));
currentLine++; words = words.splice(idx - 1); idx = 1;} else { idx++; }} if (idx > 0){ outLines.push(words.join(" "));}} currentLine++;}
var maxW=0; for (i=0; i<outLines.length; i++){ if (context.measureText(outLines[i]).width>maxW){maxW=context.measureText(outLines[i]).width}}
for (i=0; i<outLines.length-1; i++){ var wordsLine = outLines[i].split(" "); var indexB=1; var space="  "; while (context.measureText(outLines[i]).width<maxW && indexB>0){ var newLine=""; for (j=0; j<wordsLine.length; j++){ if (j<indexB){
newLine=newLine+wordsLine[j]+space;} else{ newLine=newLine+wordsLine[j]+" ";}} outLines[i]=$.trim(newLine);indexB+=1;if (indexB>wordsLine.length){
indexB=1; space=space+" "} if (i==outLines.length-2){indexB=0;}}} return outLines;}
function roundedRect(ctx,x,y,width,height,radius,color){ ctx.beginPath(); ctx.moveTo(x,y+radius); ctx.lineTo(x,y+height-radius); ctx.quadraticCurveTo(x,y+height,x+radius,y+height);ctx.lineTo(x+width-radius,y+height);
ctx.quadraticCurveTo(x+width,y+height,x+width,y+height-radius); ctx.lineTo(x+width,y+radius); ctx.quadraticCurveTo(x+width,y,x+width-radius,y); ctx.lineTo(x+radius,y); ctx.quadraticCurveTo(x,y,x,y+radius);ctx.closePath();ctx.stroke();
if (color!=""){ if (color.substr(0,9)=="gradient_"){ var my_gradient=ctx.createLinearGradient(x+width/2,y,x+width/2,y+height); my_gradient.addColorStop(0,color.substr(9,20)); my_gradient.addColorStop(1,"white");
ctx.fillStyle=my_gradient; ctx.fill();} else{ ctx.fillStyle=color; ctx.fill();}}}
 function drawDashedLine(context, fromX, fromY, toX, toY, dashPattern) {context.beginPath();var dx = toX - fromX;var dy = toY - fromY;var angle = Math.atan2(dy, dx);var x = fromX;var y = fromY;context.moveTo(fromX, fromY);var idx = 0;var draw = true;
while (!((dx < 0 ? x <= toX : x >= toX) && (dy < 0 ? y <= toY : y >= toY))) {var dashLength = dashPattern[idx++ % dashPattern.length];var nx = x + (Math.cos(angle) * dashLength);x = dx < 0 ? Math.max(toX, nx) : Math.min(toX, nx);var ny = y + (Math.sin(angle) * dashLength);y = dy < 0 ? Math.max(toY, ny) : Math.min(toY, ny);
if (draw) {context.lineTo(x, y);} else { context.moveTo(x, y);} draw = !draw;} context.closePath();context.stroke();};
function paintBubble(ctx, x, y, w, h, xPointer, radius) {if (xPointer == 0) {var xP = x + w / 2;} else {var xP = xPointer;}ctx.fillStyle = colorSele;ctx.globalAlpha = 0.7;ctx.beginPath();ctx.strokeStyle = colorSele;
ctx.lineWidth = "2";roundedRect(ctx, x, y, w, h - 10, 10, colorSele);ctx.moveTo(xP, y + h - 10);ctx.lineTo(xP + 10, y + h - 10);ctx.lineTo(xP + 5, y + h);ctx.lineTo(xP, y + h - 10);ctx.shadowColor = "#999";ctx.shadowBlur = 5;ctx.shadowOffsetX = 3;ctx.shadowOffsetY = 3;ctx.fill();ctx.stroke();}
function showMessage(typeMessage) {var h_font=14;var verticalOffset=h_font+6;var rectHeight=h_font+16;var oldTypeGame = typeGame;typeGame = 99;isShowMessage = true;var textMessage, urlMessage, goURLTarget, borderColor;if (typeMessage === "Ok") {textMessage = messageOk;urlMessage = urlOk;goURLTarget = goURLOk;borderColor = borderOk;} else if (typeMessage === "scoMessage") {textMessage = scoMessage;urlMessage = "";goURLTarget = "";borderColor = borderAttempts;} else if (typeMessage === "Time") {textMessage = messageTime;urlMessage = urlTime;goURLTarget = goURLTime;borderColor = borderTime;} else if (typeMessage === "Error") {textMessage = messageError;urlMessage = urlError;goURLTarget = goURLError;borderColor = borderError;} else if (typeMessage === "Attempts") {if (tiTime || tiAttempts || tiScore || tiSuccesses) {clearInterval(timeInterval);};textMessage = messageAttempts;urlMessage = urlAttempts;goURLTarget = goURLAttempts;borderColor = borderAttempts;}
var svg = document.getElementById("ardoraActSVG");if (!svg) {svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");svg.setAttribute("id", "ardoraActSVG");svg.style.position = "absolute";svg.style.top = "0";svg.style.left = "0";svg.style.width = "100%";svg.style.height = "100%";svg.style.zIndex = 5000;document.getElementById("ardoraAct").appendChild(svg);};svg.style.visibility = "visible";while (svg.firstChild) {svg.removeChild(svg.firstChild);};var container = document.getElementById("ardoraAct");var width = container.offsetWidth;var height = container.offsetHeight;svg.setAttribute("viewBox", "0 0 " + width + " " + height);var bgRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");bgRect.setAttribute("x", 0);bgRect.setAttribute("y", 0);bgRect.setAttribute("width", width);bgRect.setAttribute("height", height);bgRect.setAttribute("fill", colorBack);bgRect.setAttribute("opacity", 0.8);svg.appendChild(bgRect);
var tempText = document.createElementNS("http://www.w3.org/2000/svg", "text");tempText.setAttribute("font-family", fMenssage);tempText.setAttribute("font-size", h_font + "px");tempText.textContent = textMessage;svg.appendChild(tempText);var bbox = tempText.getBBox();var metricsW = bbox.width;svg.removeChild(tempText);var xText = (width / 2) - (metricsW / 2);var yText = height / 2;
function addText(txt, x, y) {var finalText = document.createElementNS("http://www.w3.org/2000/svg", "text");finalText.setAttribute("x", x);finalText.setAttribute("y", y);finalText.setAttribute("font-family", fMenssage);finalText.setAttribute("font-size", h_font + "px");finalText.setAttribute("fill", "black");finalText.setAttribute("filter", "url(#dropShadow)");finalText.textContent = txt;svg.appendChild(finalText);}
if (metricsW < width - 20) {var borderRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");var xAnim = width / 2;var wAnim = 0;var borderSh = document.createElementNS("http://www.w3.org/2000/svg", "rect");borderSh.setAttribute("x", xAnim + 4);borderSh.setAttribute("y", yText - verticalOffset + 4);borderSh.setAttribute("width", wAnim);borderSh.setAttribute("height", rectHeight);borderSh.setAttribute("fill", "gray");borderSh.setAttribute("stroke-width", 0);borderSh.setAttribute("rx", 5);borderSh.setAttribute("ry", 5);borderSh.setAttribute("opacity", 0.3);svg.appendChild(borderSh);borderRect.setAttribute("x", xAnim);borderRect.setAttribute("y", yText - verticalOffset);borderRect.setAttribute("width", wAnim);borderRect.setAttribute("height", rectHeight);borderRect.setAttribute("fill", "white");borderRect.setAttribute("stroke", borderColor);borderRect.setAttribute("stroke-width", 2);borderRect.setAttribute("rx", 5);borderRect.setAttribute("ry", 5);svg.appendChild(borderRect);var targetWidth = metricsW + 30;
var animation = setInterval(function() {wAnim += 2;xAnim -= 1;borderRect.setAttribute("x", xAnim);borderRect.setAttribute("width", wAnim);borderSh.setAttribute("x", xAnim);borderSh.setAttribute("width", wAnim + 4);if (wAnim >= targetWidth) {clearInterval(animation);addText(textMessage, xText, yText);messagePlayAudio(typeMessage);goURL(urlMessage, timeOnMessage, goURLTarget, typeMessage, tiTimeType);}}, 1);}
else {var words = textMessage.split(" ");var lines = [];var currentLine = "";var temp = document.createElementNS("http://www.w3.org/2000/svg", "text");temp.setAttribute("font-family", fMenssage);temp.setAttribute("font-size", h_font + "px");svg.appendChild(temp);for (var i = 0; i < words.length; i++) {var testLine = currentLine ? currentLine + " " + words[i] : words[i];temp.textContent = testLine;if (temp.getBBox().width > width - 100 && currentLine !== "") {lines.push(currentLine);currentLine = words[i];} else {currentLine = testLine;}}
lines.push(currentLine);svg.removeChild(temp);var totalHeight = rectHeight * lines.length;var startY = (height / 2) - (totalHeight / 2);var borderRectMulti = document.createElementNS("http://www.w3.org/2000/svg", "rect");var xAnimMulti = width / 2;var wAnimMulti = 0;borderRectMulti.setAttribute("x", xAnimMulti);borderRectMulti.setAttribute("y", (height / 2) - (rectHeight * lines.length / 2));borderRectMulti.setAttribute("width", wAnimMulti);borderRectMulti.setAttribute("height", rectHeight * lines.length + verticalOffset);borderRectMulti.setAttribute("fill", "white");borderRectMulti.setAttribute("stroke", borderColor);borderRectMulti.setAttribute("stroke-width", 2);borderRectMulti.setAttribute("rx", 5);borderRectMulti.setAttribute("ry", 5);svg.appendChild(borderRectMulti);
var targetWidthMulti = width - 80;var animationMulti = setInterval(function() {wAnimMulti += 2;xAnimMulti -= 1;borderRectMulti.setAttribute("x", xAnimMulti);borderRectMulti.setAttribute("width", wAnimMulti);if (wAnimMulti >= targetWidthMulti) {clearInterval(animationMulti);for (var j = 0; j < lines.length; j++) {addText(lines[j], 50, (height / 2) - (rectHeight * lines.length / 2) + ((j + 1) * rectHeight));};messagePlayAudio(typeMessage);goURL(urlMessage, timeOnMessage, goURLTarget, typeMessage, tiTimeType);}}, 1);}
svg.style.zIndex = 5000;if (typeMessage === "Error") {backAct(timeOnMessage, oldTypeGame);};if (typeMessage === "Time") {if (tiTimeType === 1) {timeAct = timeIni;backTime(timeOnMessage);backAct(timeOnMessage, oldTypeGame);};if (tiTimeType === 2) {backSol(timeOnMessage, oldTypeGame);}};if (typeMessage=="Next") {backAct(timeOnMessage, oldTypeGame);}
}
function backAct(seg,oldTypeGame){setTimeout(function(){paintBack();isShowMessage=false;
document.getElementById("ardoraActSVG").style["visibility"]="hidden";typeGame=oldTypeGame;
},seg*1000);}
function paintButtonTime() {var h_font=14;var verticalOffset=h_font+6;var rectHeight=h_font+16;var svg=document.getElementById("ardoraActSVG");svg.style.zIndex=5;svg.style.visibility="visible";document.getElementById("ardoraTab").style.visibility="hidden";svg.style.cursor="pointer";svg.setAttribute("tabindex", "0");if (tiTime || tiAttempts || tiScore || tiSuccesses) {clearInterval(timeInterval);};while (svg.firstChild) {svg.removeChild(svg.firstChild);};var bbox=svg.getBoundingClientRect();var width=bbox.width;var height=bbox.height;
var bgRect=document.createElementNS("http://www.w3.org/2000/svg", "rect");bgRect.setAttribute("x", 0);bgRect.setAttribute("y", 0);bgRect.setAttribute("width", width);bgRect.setAttribute("height", height);bgRect.setAttribute("fill", colorButton);bgRect.setAttribute("fill-opacity", 0.98);svg.appendChild(bgRect);var borderRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");borderRect.setAttribute("x", 5);borderRect.setAttribute("y", 5);borderRect.setAttribute("width", width - 10);borderRect.setAttribute("height", height - 10);borderRect.setAttribute("fill","none");borderRect.setAttribute("stroke",colorSele);borderRect.setAttribute("stroke-width",2);svg.appendChild(borderRect);
var tempText = document.createElementNS("http://www.w3.org/2000/svg", "text");tempText.setAttribute("x", -9999);tempText.setAttribute("y", -9999);tempText.setAttribute("font-family", fMenssage);tempText.setAttribute("font-size", h_font + "px");tempText.textContent = textButtonTime;svg.appendChild(tempText);var textBBox = tempText.getBBox();var metricsW = textBBox.width;svg.removeChild(tempText);var xText = (width / 2) - (metricsW / 2);var yText = height / 2 + (h_font / 2 - 2);var animRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");animRect.setAttribute("x", width / 2);animRect.setAttribute("y", yText - verticalOffset);animRect.setAttribute("width", 0);animRect.setAttribute("height", rectHeight);animRect.setAttribute("rx", 5);animRect.setAttribute("ry", 5);animRect.setAttribute("fill", colorBack);svg.appendChild(animRect);
var xAnim = width / 2;var wAnim = 0;var interval = setInterval(function() {xAnim -= 1;wAnim += 2;animRect.setAttribute("x", xAnim);animRect.setAttribute("width", wAnim);if (wAnim > metricsW + rectHeight) {clearInterval(interval);var group = document.createElementNS("http://www.w3.org/2000/svg", "g");var fillRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");fillRect.setAttribute("x", animRect.getAttribute("x"));fillRect.setAttribute("y", animRect.getAttribute("y"));fillRect.setAttribute("width", animRect.getAttribute("width"));fillRect.setAttribute("height", animRect.getAttribute("height"));fillRect.setAttribute("rx", animRect.getAttribute("rx"));fillRect.setAttribute("ry", animRect.getAttribute("ry"));fillRect.setAttribute("fill", colorBack);fillRect.style.filter = "drop-shadow(6px 6px 4px rgba(136,136,136,0.5))";
var strokeRect = document.createElementNS("http://www.w3.org/2000/svg", "rect");strokeRect.setAttribute("x", animRect.getAttribute("x"));strokeRect.setAttribute("y", animRect.getAttribute("y"));strokeRect.setAttribute("width", animRect.getAttribute("width"));strokeRect.setAttribute("height", animRect.getAttribute("height"));strokeRect.setAttribute("rx", animRect.getAttribute("rx"));strokeRect.setAttribute("ry", animRect.getAttribute("ry"));strokeRect.setAttribute("fill", "none");strokeRect.setAttribute("stroke", colorText);strokeRect.setAttribute("stroke-width", 2);group.appendChild(fillRect);group.appendChild(strokeRect);svg.replaceChild(group, animRect);var textElem = document.createElementNS("http://www.w3.org/2000/svg", "text");textElem.setAttribute("x", xText);textElem.setAttribute("y", yText);textElem.setAttribute("font-family", fMenssage);textElem.setAttribute("font-size", h_font + "px");textElem.setAttribute("fill", colorText);textElem.textContent = textButtonTime;svg.appendChild(textElem);}}, 1);
function handleButtonActivation(e) {if (e.type === "keydown") {if (e.keyCode !== 13 && e.keyCode !== 32) return;e.preventDefault();};if (tiTime || tiAttempts || tiScore || tiSuccesses) {timeInterval = setInterval(function() {paintTab();}, 1000);$("#ardoraActSVG").off("mousedown touchstart keydown");svg.style.cursor = "default";svg.style.zIndex = 0;svg.style.visibility = "hidden";document.getElementById("ardoraTab").style.visibility = "visible";paintBack();}};$("#ardoraActSVG").on("mousedown touchstart keydown", handleButtonActivation);}
function messagePlayAudio(typeMessage){ if (typeMessage=="Time"){document.getElementById("audioTempo").play()}}
function backTime(seg){ setTimeout(function(){timeInterval=setInterval("paintTab()",1000);isShowMessage=false;},seg*1000);}
function backSol(seg,oldTypeGame){setTimeout(function(){showSol(oldTypeGame);},seg*1000);}
function goURL(url,seg,tar,tM,tT){var state;if (tM == "Ok") {state="ok";};if (tM == "Attempts"){state="erro";};if (tM == "Error"){state="erro";};if (tM == "Time"){state="temp";};if (tiAval){parent.actualizaInfoAct(score,attempts,state);}
newWin = setTimeout("opURL('"+url+"','"+seg+"','"+tar+"','"+tM+"','"+tT+"')",seg*1000);}
function opURL(url, seg, tar, tM,tT) {if (url != "") {window.open(url,tar)};if (tM == "Ok" && goURLNext ) {parent.avanza();};if (tM == "Attempts" && goURLRepeat){parent.recarga()};if (tM == "Time" && tT==0 && goURLRepeat){parent.recarga()};if (tM == "Time" && tT==2 && goURLRepeat){parent.recarga()}}
function cssColors(){
$("body").css("background-color",colorBack);$("#ardoraMain").css("color",colorText);$("#ardoraMain").css("font-family",fEnun);$("#ardoraAct").css("font-family",fActi);$("#ardoraTag").css("font-family",fActi);
$(".bGame").css("backgroundColor",colorButton);$(".bGame").css("color",colorBack);
}
